### ISSUE TITLE
Offerwall integration with Static API - Android

### ISSUE THREAD

**Issue by Noblepal** [AdGem/Android-Example#12]
Hi, I am having an issue with offerwall integration using **Android SDK** whereby the app is not receiving a callback when an offer has been completed. This has happened on both my app and on the sample app in this repository.

**Comment by mquirk8** [comment]
Hi, sorry to hear of the trouble you've been experiencing. We've not had any issues with conversion postbacks reported but with some more information about your app and environment I am sure we can figure out a solution. Can you confirm that you've signed up as an AdGem publisher? And have created an AdGem app in the dashboard?
