### ISSUE TITLE
Crash when debuggable is set to false

### ISSUE THREAD

**Issue by AiwNexT** [AdGem/Android-Example#16]
Sadly, I have to report the same issue again. However, this time it happens after setting the `debuggable` flag to `false` in the module's `build.gradle` file. Here is the crash log:
```
FATAL EXCEPTION: main
    Process: com.adgem.android.example, PID: 7283
    java.lang.NullPointerException
        at com.adgem.android.internal.g$a.onResponse(SourceFile:2)
        at com.adgem.android.internal.g$c.onResponse(Unknown Source:13)
        at s3.l$a$a$a.run(Unknown Source:37)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8210)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```
It's very easy to reproduce this issue. Just open your `Android-Example` project and add the following code in your `build.gradle` file:
```
buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            initWith debug

            minifyEnabled true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
```
Since setting `debuggable` to `false` is highly recommended in terms of security + Android Studio won't let you sign the release build unless this flag is set to `false`, this is a major issue.

**Comment by AiwNexT** [comment]
@Exaper I would appreciate if you take a look at this issue

**Comment by Exaper** [comment]
@AiwNexT just to confirm, this is on v3.2.0?

**Comment by AiwNexT** [comment]
@Exaper Yes, it's v3.2.0. I just pulled the latest changes from the master branch and added the `buildTypes` block.

**Comment by AiwNexT** [comment]
And of course switch the build type to release before running on the device in order to reproduce the issue please

**Comment by Exaper** [comment]
Hi! Thanks for checking in. We are investigating it ATM. Will have something real soon.

**Comment by AiwNexT** [comment]
@Exaper Hi! Do you have any updates? When do you guys plan to fix this issue?

**Comment by NedkoBrymchev** [comment]
@Exaper how it is going? Is there any rough estimate for the new version?

**Comment by Exaper** [comment]
We should have something out this week. Thanks for checking in!

**Comment by AiwNexT** [comment]
@Exaper Hi! It's been 12 days since your last comment. And it's almost 2 weeks. Do you have any updates?

**Comment by Exaper** [comment]
This seems to be not an issue. Here's why:
When declaring `debug` or `release` build types gradle already propagates `debuggable` flag (since debug{} and release{} clauses are *configurations*, not a new definitions). More on the topic: http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Types - see when they specifically mention that each build type propagates correct flag to the final AndroidManifest produced by aapt.
It's easy to confirm - produce debug and release builds of your application without explicitly declaring `debuggable false` - open up resulting APKs with any analyzer tool (or on-device `jdwp` tool) to verify that debuggable flag is correctly set.

Now on the open question *why* the crash occurs. My suspicion is that setting explicit debuggable flag in build.gradle messes up R8/Proguard obfuscation pass (which in turn strips out necessary classes retrofit depends on). This in turn creates NPE. Invalid fix would be to handle NPE with plain-old `if` check. That would not solve the high-level problem:  
 server response will not be consumed. SDK won't work as expected.

My suggestion - leave out `debugable false` flag. Gradle/Android Studio will automatically propagate it depending on the build type being generated.

**Comment by AiwNexT** [comment]
@Exaper Ok, I removed the `debuggable false`, as you suggested. However, the crash still occurs every time the app is launched. I did some testing and found the only way to avoid this crash. It is to remove the following line: `proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'`. But we can't do that, because it contains a lot of rules for other SDKs. So, could you please provide R8/Proguard rules for AdGem SDK?

And also, I have a question: why did you decide to embed Retrofit inside the SDK? It's much better to include external libraries as `api` instead of using `implementation` and embedding the whole library into the SDK.

**Comment by Exaper** [comment]
So gradle pulls in library's proguard file automatically. According to integration docs there is no additional proguard config needed. Here's how library's proguard looks like:

```
# Imported by library consumer

# Already obfuscated
-keep class com.adgem.android.internal.** { *; }

# Using reflection to access AdvertisingIdClient and acuire Google Ad ID.
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient { *; }
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info { *; }

# Retrofit
-dontwarn javax.annotation.**

# We use androidx only at compile time. Consumer application should not care.
-dontwarn androidx.annotation.**

# OKIO
-dontwarn okio.**
-dontwarn okhttp3.**
-dontwarn org.codehaus.**
```

As for the `api` vs `implementation`, I believe we are scoping this the right way: `api` scope implies that the library would expose its dependency's api (hence consuming application would be able to use retrofit's api). This is not the intention, is it?

**Comment by Exaper** [comment]
`compileOnly` will have to force developers (you guys) add all necessary libraries that we depend on. This is not a standard practice in this industry. Imagine Glide or Picasso requiring adding okhttp dependency when integrating with it, would it be desirable? I am open to suggestions, but looking around, this is not how libraries are distributed these days.

**Comment by Exaper** [comment]
Were you able to see the crash when generating release build out of example application?

**Comment by Exaper** [comment]
Can you try using `proguardFiles getDefaultProguardFile('proguard-android.txt')` instead? `proguard-android-optimize` might be too aggressive.

**Comment by Exaper** [comment]
I guess it's uncommon to use `proguard-android-optimize.txt` in prod-level apps. Happy we got it resolved.

**Comment by AiwNexT** [comment]
Got it. Thanks.
