### ISSUE TITLE
Fastlane Publish to Firebase App Distribution

### ISSUE THREAD

**Issue by nhaynes** [AdGem/Android-Example#21]
We want to add Fastlane to this project and use it to publish newly released versions to the play store.

We will need to add a new `release` workflow that executes when a new version is released to github (via Semantic release)

**Comment by nhaynes** [comment]
@mawalker is this one complete?

**Comment by dakotawashok** [comment]
![image](https://github.com/AdGem/Android-Example/assets/10078874/a2bd025b-ae36-4ada-ac64-f9a39c331be9)
