### ISSUE TITLE
Need java version example 

### ISSUE THREAD

**Issue by sahujaunpuri** [AdGem/Android-Example#8]
Need java version example

**Comment by Exaper** [comment]
@sahujaunpuri could you please elaborate on this request? Example source code already includes example setting up Java for your project. Please see https://github.com/AdGem/Android-Example/blob/master/app/build.gradle

Thanks!

**Comment by sahujaunpuri** [comment]
> @sahujaunpuri could you please elaborate on this request? Example source code already includes example setting up Java for your project. Please see https://github.com/AdGem/Android-Example/blob/master/app/build.gradle
> 
> Thanks!

https://github.com/AdGem/Android-Example/blob/master/app/build.gradle 
Because **kotlin** is used in above link. I want complete code in Java only with out using kotlin.

**Comment by abdelrhman17** [comment]
I need the hosting file

**Comment by Exaper** [comment]
@abdelrhman17 please sign up for one at adgem.com

**Comment by abdelrhman17** [comment]
I already have an account on adgem

**Comment by nhaynes** [comment]
Closing stale issue.
